blinking-cursor = true
theme = 'catppuccin-frappe'

[fonts]
size = 15
family = "FiraCode Nerd Font Mono"

[fonts.regular]
family = "FiraCode Nerd Font Mono"
style = "normal"
weight = 400

[fonts.bold]
family = "FiraCode Nerd Font Mono"
style = "normal"
weight = 800

[fonts.italic]
family = "FiraCode Nerd Font Mono"
style = "italic"
weight = 400

[fonts.bold-italic]
family = "FiraCode Nerd Font Mono"
style = "italic"
weight = 800

[navigation]
mode = "NativeTab"

