# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []

# Start AeroSpace at login
start-at-login = true

accordion-padding = 0

[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 10
outer.bottom = 10
outer.top = 10
outer.right = 10

[mode.main.binding]

#
# Disable annoying MacOS shortcuts
#
cmd-h = []       # Disable "hide application"
cmd-alt-h = []   # Disable "hide others"
cmd-shift-m = [] # Disable "open terminal"

# i3 wraps focus by default
alt-j = 'focus --boundaries-action wrap-around-the-workspace left'
alt-k = 'focus --boundaries-action wrap-around-the-workspace down'
alt-l = 'focus --boundaries-action wrap-around-the-workspace up'
alt-semicolon = 'focus --boundaries-action wrap-around-the-workspace right'

alt-shift-j = 'move left'
alt-shift-k = 'move down'
alt-shift-l = 'move up'
alt-shift-semicolon = 'move right'

# Consider using 'join-with' command as a 'split' replacement if you want to enable normalizations
alt-h = 'join-with right'
alt-v = 'join-with down'

alt-f = 'fullscreen'

alt-s = 'layout v_accordion' # 'layout stacking' in i3
alt-w = 'layout h_accordion' # 'layout tabbed' in i3
alt-x = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-t = 'workspace T'
alt-c = 'workspace C'
alt-b = 'workspace B'
alt-d = 'workspace D'
alt-e = 'workspace E'
alt-n = 'workspace N'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-t = 'move-node-to-workspace T'
alt-shift-c = 'move-node-to-workspace C'
alt-shift-b = 'move-node-to-workspace B'
alt-shift-d = 'move-node-to-workspace D'
alt-shift-e = 'move-node-to-workspace E'
alt-shift-n = 'move-node-to-workspace N'

alt-ctrl-c = 'reload-config'

alt-r = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

# alt-space = ['mode move']


# [mode.move.binding]
# space = ['mode main']
# esc = ['mode main']
# backtick = ['reload-config', 'mode main']
#
# #
# # Layout
# #
# a = ['layout accordion']
# t = ['layout tiles']
#
# #
# # Navigation
# #
#
# h = ['focus left']
# j = ['focus down']
# k = ['focus up']
# l = ['focus right']
#
# 1 = 'workspace 1'
# 2 = 'workspace 2'
# 3 = 'workspace 3'
# 4 = 'workspace 4'
# 5 = 'workspace 5'
# 6 = 'workspace 6'
# 7 = 'workspace 7'
# 8 = 'workspace 8'
# 9 = 'workspace 9'
#
# tab = 'workspace-back-and-forth'
#
# #
# # Moving
# #
#
# shift-h = ['move left']
# shift-j = ['move down']
# shift-k = ['move up']
# shift-l = ['move right']
#
# alt-h = 'join-with left'
# alt-j = 'join-with down'
# alt-k = 'join-with up'
# alt-l = 'join-with right'
#
# shift-1 = 'move-node-to-workspace 1'
# shift-2 = 'move-node-to-workspace 2'
# shift-3 = 'move-node-to-workspace 3'
# shift-4 = 'move-node-to-workspace 4'
# shift-5 = 'move-node-to-workspace 5'
# shift-6 = 'move-node-to-workspace 6'
# shift-7 = 'move-node-to-workspace 7'
# shift-8 = 'move-node-to-workspace 8'
# shift-9 = 'move-node-to-workspace 9'
#
# #
# # Resizing
# #
#
# m = ['fullscreen']
# minus = 'resize smart -10'
# equal = 'resize smart +10'
# shift-minus = 'resize smart -50'
# shift-equal = 'resize smart +50'
#
# #
# # Other
# #
#
# r = ['flatten-workspace-tree']

#
# App Placements
#


[[on-window-detected]]
if.app-name-regex-substring = 'Ghostty|iTerm|Zed'
run = ['layout tiling', 'move-node-to-workspace T']

[[on-window-detected]]
if.app-name-regex-substring = 'Xcode'
run = ['layout tiling', 'move-node-to-workspace E']

[[on-window-detected]]
if.app-name-regex-substring = 'Simulator|Podman'
run = ['layout tiling', 'move-node-to-workspace D']

[[on-window-detected]]
if.app-name-regex-substring = 'Arc|Chrome|Zen'
run = ['layout tiling', 'move-node-to-workspace B']

[[on-window-detected]]
if.app-name-regex-substring = 'Slack|Teams|Zoom'
run = ['layout tiling', 'move-node-to-workspace C']

[[on-window-detected]]
if.app-name-regex-substring = 'Obsidian|Notes'
run = ['layout tiling', 'move-node-to-workspace N']

[[on-window-detected]]
if.app-name-regex-substring = 'Spotify|Finder'
run = ['layout tiling', 'move-node-to-workspace 1']
