#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)
source "$DOTFILES_ROOT/script/utils"

CODE_VOLUME_NAME="Repositories"
CODE_SYMLINK_NAME="Repos"

if ! [[ -d "/Volumes/$CODE_VOLUME_NAME" ]]; then
  info '> create repositories volume'
  diskutil apfs addVolume disk1 "Case-sensitive APFS" $CODE_VOLUME_NAME -passprompt | indent
fi

if ! [ -L "$HOME/Repos" ]; then
  info "> symlink repositories volume to home directory"
  ln -s  "/Volumes/$CODE_VOLUME_NAME" "$HOME/$CODE_SYMLINK_NAME"
fi

# info '> set macos defaults'
# source $DOTFILES_ROOT/macos/defaults

success '> macos'
