#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)
source "$DOTFILES_ROOT/script/utils"

if [ hash apm 2>/dev/null ]; then
  info '> install atom packages'
  apm install --packages-file './atom/packages.txt' | indent

  success '> atom'
fi
