#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)
source "$DOTFILES_ROOT/script/utils"

if [ -x $(command -v hyper) ]; then
  info '> install hyper extensions'
  EXTENSIONS=$(cat ./hyper/extensions.txt)
  for extension in $EXTENSIONS; do
    hyper install $extension | indent
  done

  success '> hyper'
fi
