#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)
source "$DOTFILES_ROOT/script/utils"

if ! [ -x "$(command -v brew)" ]; then
  info '> install brew'
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  source "$DOTFILES_ROOT/homebrew/config.zsh"
fi

if [ -x "$(command -v brew)" ]; then
  info '> brew update'
  brew update

  info '> brew bundle'
  brew bundle --file="./homebrew/Brewfile"

  info '> brew cleanup'
  brew cleanup
fi

success '> brew'
