cask_args appdir: "/Applications"

brew "coreutils"
brew "diff-so-fancy"
brew "git"

cask "1password"
cask "docker"
cask "figma"
cask "google-chrome"
cask "iterm2"
cask "kap"
cask "keepingyouawake"
cask "nordvpn"
cask "quicklook-json"
cask "slack"
cask "spectacle"
cask "spotify"
cask "visual-studio-code"
cask "whatsapp"

tap "homebrew/cask-fonts"

cask "font-fira-code"
