cask_args appdir: "/Applications"

brew "coreutils"
brew "curl"
brew "diff-so-fancy"
brew "git"
brew "gpg" # for asdf nodejs
brew "zsh"

# This depends on coreutils, curl & git
brew "asdf"

cask "1password"
cask "alfred"
cask "docker"
cask "figma"
cask "google-chrome"
cask "iterm2"
cask "kap"
cask "keepingyouawake"
cask "nordvpn"
cask "quicklook-json"
cask "slack"
cask "spectacle"
cask "spotify"
cask "visual-studio-code"
cask "whatsapp"

tap "homebrew/cask-fonts"

cask "font-fira-code"
cask "font-cascadia-code"
