#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)
source "$DOTFILES_ROOT/script/utils"

info '> brew update'
brew update | indent

info '> brew bundle'
brew bundle --file="./homebrew/Brewfile" | indent

info '> brew cleanup'
brew cleanup | indent

success '> brew'
