#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)
source "$DOTFILES_ROOT/script/utils"

run_bootstraps() {
  local bootstrap_files=$(find_files 'bootstrap')

  info '> bootstrap'
  for file in $bootstrap_files; do
    if ! sh "$file"; then
      fail "$file"
    fi
  done
  success '> bootstrap'
}

add_symlinks() {
  local symlinks=$(find_files '*.symlink')

  info '> symlinks'
  for src in $symlinks; do
    local dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
  success '> symlinks'
}

run_bootstraps
add_symlinks

info '> please open a new terminal tab & run "c dotfiles"'
