#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)
source "$DOTFILES_ROOT/script/utils"

run_pre_bootstraps() {
  local bootstrap_files=$(find_files 'pre-bootstrap')

  info '> pre-bootstrap'
  for file in $bootstrap_files; do
    if ! sh "$file"; then
      fail "$file"
    fi
  done
  success '> pre-bootstrap'
}

mkdir -p $DOTFILES_ROOT/downloads

run_pre_bootstraps

if [[ -f "$HOME/Repos/dotfiles" ]]; then
  mv "$DOTFILES_ROOT" "$HOME/Repos"
fi

cd "$HOME/Repos/dotfiles"
