#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)
source "$DOTFILES_ROOT/script/utils"

if [ -f "$HOME/.asdf" ]; then
  info '> asdf clone'
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.10.2
  source "$DOTFILES_ROOT/asdf/config.zsh"
  success '> asdf cloned & loaded'
fi

if [ -x "$(command -v asdf)" ]; then
  plugins=$(awk <"$DOTFILES_ROOT/asdf/tool-versions.symlink" '{ print $1 }')

  for plugin in $plugins; do
    info "> asdf plugin add $plugin"
    asdf plugin add "$plugin" | indent
  done

  info '> asdf install'
  cd ~ && asdf install

  success '> asdf'
else
  fail '> asdf not found'
fi
