return {}
-- return {
--   {
--     "huggingface/llm.nvim",
--     opts = {
--       backend = "ollama",
--       model = "deepseek-r1:14b",
--       tls_skip_verify_insecure = true,
--       url = "http://localhost:11434",
--     },
--   },
-- }
