#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)
source "$DOTFILES_ROOT/script/utils"

ZSH_CUSTOM=${ZSH_CUSTOM:-~/.oh-my-zsh/custom}

if ! [ -d "$HOME/.oh-my-zsh" ]; then
  info '> install oh-my-zsh'
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi

if ! [ -f "$DOTFILES_ROOT/zsh/antigen.zsh" ]; then
  info '> download antigen'
  curl -L git.io/antigen >"$DOTFILES_ROOT/downloads/antigen.zsh"
fi

success '> zsh'
