#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)
source "$DOTFILES_ROOT/script/utils"

if ! [ -f "$DOTFILES_ROOT/downloads/Relaxed.itermcolors" ]; then
  info '> item download relaxed theme'
  curl -L https://gitcdn.link/repo/mischah/Relaxed/master/themes/Relaxed.itermcolors -o "$DOTFILES_ROOT/downloads/Relaxed.itermcolors" --silent | indent
fi

if ! [ -f "$DOTFILES_ROOT/downloads/palenight.itermcolors" ]; then
  info '> item download palenight theme'
  curl -L https://raw.githubusercontent.com/JonathanSpeek/palenight-iterm2/master/palenight.itermcolors -o "$DOTFILES_ROOT/downloads/palenight.itermcolors" --silent | indent
fi

success '> iterm'
